# -*- coding: utf-8 -*-
"""Week3/A106260093/王緯華.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KSQkFJV2tfguyRbYsncfNBmjIf8t_SEb
"""

print("HelloWorld")

print("我是王緯華")

